server:
  port: 8082

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  application:
    name: upload-service
  datasource:
    url: jdbc:mysql://localhost:3306/INSTAGRAM?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl:
          auto: none

cloudinary:
  cloud-name: hura
  api-key: hura
  api-secret: hura


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka  # Cấu hình Eureka để kết nối với server Eureka
